sudo: require

language: go

services:
 - docker

before_script:
 - docker login --email "${DOCKER_EMAIL}" --password "${DOCKER_PASSWORD}" --username "${DOCKER_USER}" "${DOCKER_REGISTRY}"

script:
  - make
  - make push
